### ISSUE TITLE
ImageCard 마우스 오버시 효과가 카드를 넘어가는 문제

### ISSUE THREAD

**Issue by kimjeongwonn** [team-badminton/imgar-frontend#109]
**문제 상황 설명**
style에서 overflow: hidden 추가하면 해결될 것 같아요

**캡쳐 화면**
![image](https://user-images.githubusercontent.com/66168187/135554896-afba556b-81d2-48ce-ab64-9961972ee216.png)

**Comment by HyunJungC-Dev** [comment]
마우스 호버 시 효과는 ImageCard의 after에 해당하여
ImageCard에 overflow: hidden을 주어 after가 본인을 넘어가지 못하도록 수정

**Comment by HyunJungC-Dev** [comment]
#112 PR 보냈습니다.
