### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by Ruriko** [team-badminton/imgar-frontend#217]
Can you add reverse proxy to images so the url looks like it's coming from own domain

**Comment by yeongjong310** [comment]
> Can you add reverse proxy to images so the url looks like it's coming from own domain

Can I ask you why the url needs to look like coming from own domain?

**Comment by Ruriko** [comment]
So it doesn't look like it's hotlinking but actually serving images on own server. By using reverse proxy you can cache images and it'll load images faster

**Comment by Ruriko** [comment]
Another reason to use reverse proxy is that some countries block imgur

**Comment by yeongjong310** [comment]
> So it doesn't look like it's hotlinking but actually serving images on own server. By using reverse proxy you can cache images and it'll load images faster

I got it. But I am afraid to say that we doesn't have own server. Serving images are from imgur's API. And the API requests are triggered on frontend side .
